/**
 * Pixel-art sample: a few dozen small sprites scattered over white.
 *
 * Everything is aligned to the 8x8 lattice on purpose. JPEG cuts the image into 8x8
 * blocks, so aligned sprites let a slide select a block that holds exactly one sprite —
 * or exactly one quadrant of a 16x16 one — which makes the DCT and quantisation steps
 * far easier to read than a block straddling arbitrary detail.
 *
 * Sprites are deliberately mixed: flat single-colour shapes produce a DCT that is almost
 * all DC, while the multicolour ones spread energy into the higher coefficients.
 */

const C = {
  '.': null, // transparent — leaves the white background
  k: [26, 26, 32],
  w: [255, 255, 255],
  r: [214, 48, 49],
  o: [230, 126, 34],
  y: [253, 203, 60],
  g: [46, 174, 96],
  G: [26, 122, 66],
  b: [52, 120, 246],
  B: [30, 70, 170],
  c: [72, 214, 226],
  p: [244, 143, 177],
  P: [155, 89, 182],
  s: [149, 165, 166],
  S: [99, 110, 114],
  n: [120, 78, 52],
  W: [226, 232, 250], // near-white, for sprites that would vanish on the white page
}

/** 8x8: one sprite fills exactly one JPEG block. */
export const SPRITES_8 = {
  heart: [
    '.rr..rr.',
    'rrrrrrrr',
    'rrrrrrrr',
    'rrrrrrrr',
    '.rrrrrr.',
    '..rrrr..',
    '...rr...',
    '........',
  ],
  star: [
    '...yy...',
    '...yy...',
    '.yyyyyy.',
    'yyyyyyyy',
    '.yyyyyy.',
    '..y..y..',
    '.y....y.',
    '........',
  ],
  smiley: [
    '..yyyy..',
    '.yyyyyy.',
    'yykyykyy',
    'yyyyyyyy',
    'yykyykyy',
    'yykkkkyy',
    '.yyyyyy.',
    '..yyyy..',
  ],
  cherry: [
    '.....G..',
    '....G...',
    '..G.G...',
    '.G..G...',
    'rr..rr..',
    'rrr.rrr.',
    'rrr.rrr.',
    '.r...r..',
  ],
  droplet: [
    '...bb...',
    '...bb...',
    '..bbbb..',
    '.bbbbbb.',
    'bbbbbbbb',
    'bbbbbbbb',
    '.bbbbbb.',
    '..bbbb..',
  ],
  flower: [
    '..pp.p..',
    '.pppppp.',
    '.ppyypp.',
    'ppyyyypp',
    '.ppyypp.',
    '.pppppp.',
    '...GG...',
    '...GG...',
  ],
  diamond: [
    '...cc...',
    '..cccc..',
    '.cccccc.',
    'cccccccc',
    'cccccccc',
    '.cccccc.',
    '..cccc..',
    '...cc...',
  ],
  mushroom: [
    '..rrrr..',
    '.rwrrwr.',
    'rrrrrrrr',
    'rwrrrrwr',
    'rrrrrrrr',
    '..ywwy..',
    '..ywwy..',
    '..yyyy..',
  ],
  cat8: [
    'k.....k.',
    'kk...kk.',
    'kokokoko',
    'okkokkoo',
    'ooooooo.',
    'okoookoo',
    'oopppoo.',
    '.oooooo.',
  ],
  cross: [
    '...gg...',
    '...gg...',
    '.gggggg.',
    'gggggggg',
    'gggggggg',
    '.gggggg.',
    '...gg...',
    '...gg...',
  ],
}

/** 16x16: one sprite spans a 2x2 group of blocks. */
export const SPRITES_16 = {
  robot: [
    '................',
    '......kk........',
    '......kk........',
    '..ssssssssss....',
    '.sSSSSSSSSSSs...',
    '.sSccSSSSccSs...',
    '.sSccSSSSccSs...',
    '.sSSSSSSSSSSs...',
    '.sSSkkkkkkSSs...',
    '.sSSSSSSSSSSs...',
    '..ssssssssss....',
    '...sSSSSSSs.....',
    '...s.SSSS.s.....',
    '.....SSSS.......',
    '....ss..ss......',
    '................',
  ],
  frog: [
    '................',
    '..gg........gg..',
    '.gwwg......gwwg.',
    'gwkkwg....gwkkwg',
    'gwkkwggggggwkkwg',
    '.gwwggggggggwwg.',
    '..ggggggggggggg.',
    '.ggggggggggggggg',
    '.ggggggggggggggg',
    '.GggggggggggggG.',
    '.GGkkkkkkkkkkGG.',
    '..GGGGGGGGGGGG..',
    '...GGGGGGGGGG...',
    '....GG....GG....',
    '................',
    '................',
  ],
  cat16: [
    '................',
    '..oo........oo..',
    '.oppo......oppo.',
    '.ooooo....ooooo.',
    '.oooooooooooooo.',
    'oooooooooooooooo',
    'ookkwoooooowkkoo',
    'ookkkooooookkkoo',
    'oooooooooooooooo',
    'ooooookpkoooooo.',
    'oookkkkkkkkkooo.',
    'oooookkokkooooo.',
    '.ooooooooooooo..',
    '.oooooooooooooo.',
    '..oooooooooooo..',
    '................',
  ],
  slime: [
    '................',
    '................',
    '.....bbbb.......',
    '...bbccbbbb.....',
    '..bbccbbbbbb....',
    '.bbccbbbbbbbb...',
    '.bcbbbbbbbbbb...',
    'bbbbbbbbbbbbbb..',
    'bbbbwwbbbwwbbb..',
    'bbbbwwbbbwwbbb..',
    'bbbbbbbbbbbbbb..',
    'bBbbbbwwwbbbbBb.',
    'bBBbbbbbbbbbBBb.',
    '.BBBBBBBBBBBBB..',
    '..BBBBBBBBBBB...',
    '................',
  ],
  bird: [
    '................',
    '.....bbbb.......',
    '...bbbbbbbb.....',
    '..bbbbbbbbbb....',
    '..bbkwbbbbbb....',
    '.bbbbbbbbbbb.oo.',
    '.bbbbbbbbbbbooo.',
    '.bbbBBbbbbbb.oo.',
    '.bbBBBBbbbbb....',
    '.bbbBBBbwwww....',
    '..bbbbbwwwww....',
    '...bbwwwwww.....',
    '....ww..ww......',
    '....yy..yy......',
    '................',
    '................',
  ],
  crown: [
    '................',
    '................',
    '..y..........y..',
    '..yy...yy...yy..',
    '..yy..yyyy..yy..',
    '..yyy.yyyy.yyy..',
    '..yyyyyyyyyyyy..',
    '..yyyyyyyyyyyy..',
    '..yyrryyyyrryy..',
    '..yyrryybbrryy..',
    '..yyyyyybbyyyy..',
    '..yyyyyyyyyyyy..',
    '..yyyyyyyyyyyy..',
    '................',
    '................',
    '................',
  ],
  ghost: [
    '................',
    '.....SSSSSS.....',
    '...SSWWWWWWSS...',
    '..SWWWWWWWWWWS..',
    '..SWWkkWWkkWWS..',
    '..SWWkkWWkkWWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWppWWppWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWWWWWWWWS..',
    '..SWSWWSSWWSWS..',
    '..S.SS.SS.SS.S..',
    '................',
    '................',
  ],
}

export function spriteColor(ch) {
  return C[ch] ?? null
}
