/**
 * Pixel-art sample: a dense sheet of small sprites, every one aligned to the 8x8 lattice.
 *
 * Alignment is the point. JPEG cuts the image into 8x8 blocks, so aligned sprites let a
 * slide select a block that holds exactly one 8x8 sprite, one quadrant of a 16x16, or one
 * sixteenth of a 32x32 — which makes the DCT and quantisation steps far easier to read
 * than a block straddling arbitrary detail.
 *
 * Three sizes, because they answer different questions. An 8x8 sprite *is* a block, so its
 * DCT is the sprite's own spectrum. A 16x16 or 32x32 sprite spans several blocks, so
 * neighbouring blocks hold related-but-different content — which is what makes the block
 * grid visible when quality drops.
 *
 * Sprites are deliberately mixed: flat single-colour shapes produce a DCT that is almost
 * all DC, while the multicolour ones spread energy into the higher coefficients.
 */

const C = {
  '.': null, // transparent — leaves the white background
  k: [26, 26, 32],
  w: [255, 255, 255],
  r: [214, 48, 49],
  R: [155, 30, 32],
  o: [230, 126, 34],
  y: [253, 203, 60],
  Y: [201, 152, 30],
  g: [46, 174, 96],
  G: [26, 122, 66],
  b: [52, 120, 246],
  B: [30, 70, 170],
  c: [72, 214, 226],
  p: [244, 143, 177],
  P: [155, 89, 182],
  s: [149, 165, 166],
  S: [99, 110, 114],
  n: [120, 78, 52],
  N: [82, 52, 34],
  t: [244, 197, 150],
  W: [226, 232, 250], // near-white, for sprites that would vanish on the white page
}

/** 8x8: one sprite fills exactly one JPEG block. */
export const SPRITES_8 = {
  heart: [
    '.rr..rr.',
    'rrrrrrrr',
    'rrrrrrrr',
    'rrrrrrrr',
    '.rrrrrr.',
    '..rrrr..',
    '...rr...',
    '........',
  ],
  star: [
    '...yy...',
    '...yy...',
    '.yyyyyy.',
    'yyyyyyyy',
    '.yyyyyy.',
    '..y..y..',
    '.y....y.',
    '........',
  ],
  smiley: [
    '..yyyy..',
    '.yyyyyy.',
    'yykyykyy',
    'yyyyyyyy',
    'yykyykyy',
    'yykkkkyy',
    '.yyyyyy.',
    '..yyyy..',
  ],
  cherry: [
    '.....G..',
    '....G...',
    '..G.G...',
    '.G..G...',
    'rr..rr..',
    'rrr.rrr.',
    'rrr.rrr.',
    '.r...r..',
  ],
  droplet: [
    '...bb...',
    '...bb...',
    '..bbbb..',
    '.bbbbbb.',
    'bbbbbbbb',
    'bbbbbbbb',
    '.bbbbbb.',
    '..bbbb..',
  ],
  flower: [
    '..pp.p..',
    '.pppppp.',
    '.ppyypp.',
    'ppyyyypp',
    '.ppyypp.',
    '.pppppp.',
    '...GG...',
    '...GG...',
  ],
  diamond: [
    '...cc...',
    '..cccc..',
    '.cccccc.',
    'cccccccc',
    'cccccccc',
    '.cccccc.',
    '..cccc..',
    '...cc...',
  ],
  mushroom: [
    '..rrrr..',
    '.rwrrwr.',
    'rrrrrrrr',
    'rwrrrrwr',
    'rrrrrrrr',
    '..ywwy..',
    '..ywwy..',
    '..yyyy..',
  ],
  cat8: [
    'k.....k.',
    'kk...kk.',
    'kokokoko',
    'okkokkoo',
    'ooooooo.',
    'okoookoo',
    'oopppoo.',
    '.oooooo.',
  ],
  cross: [
    '...gg...',
    '...gg...',
    '.gggggg.',
    'gggggggg',
    'gggggggg',
    '.gggggg.',
    '...gg...',
    '...gg...',
  ],
  coin: [
    '..yyyy..',
    '.yYYYYy.',
    'yYYyyYYy',
    'yYyYYyYy',
    'yYyYYyYy',
    'yYYyyYYy',
    '.yYYYYy.',
    '..yyyy..',
  ],
  key: [
    '..yyy...',
    '.y...y..',
    '.y...y..',
    '..yyy...',
    '...y....',
    '...yy...',
    '...y....',
    '...yy...',
  ],
  tree8: [
    '...G....',
    '..GGG...',
    '.GGGGG..',
    '..GGG...',
    '.GGGGG..',
    'GGGGGGG.',
    '...n....',
    '...n....',
  ],
  house: [
    '...rr...',
    '..rrrr..',
    '.rrrrrr.',
    'rrrrrrrr',
    '.WWWWWW.',
    '.WWbbWW.',
    '.WWbbWW.',
    '.WWWWWW.',
  ],
  fish: [
    '........',
    '..bbb..b',
    '.bbbbbbb',
    'bbwbbbbb',
    'bbwbbbbb',
    '.bbbbbbb',
    '..bbb..b',
    '........',
  ],
  apple: [
    '....G...',
    '...GG...',
    '.rrrrrr.',
    'rrrrrrrr',
    'rrrrrrrr',
    'rrrrrrrr',
    '.rrrrrr.',
    '..r..r..',
  ],
  bomb: [
    '......yy',
    '.....y..',
    '..kkk.y.',
    '.kkkkk..',
    'kkkkkkk.',
    'kkkwkkk.',
    '.kkkkk..',
    '..kkk...',
  ],
  note: [
    '.....kkk',
    '.....kkk',
    '.....k.k',
    '.....k.k',
    '.....k..',
    '.kkk.k..',
    'kkkkkk..',
    '.kkk....',
  ],
  envelope: [
    '........',
    'SSSSSSSS',
    'SWSSSSWS',
    'SWWSSWWS',
    'SWWWWWWS',
    'SWWWWWWS',
    'SSSSSSSS',
    '........',
  ],
  gem: [
    '........',
    '.cccccc.',
    'cbccccbc',
    'cbccccbc',
    '.cbccbc.',
    '..cbbc..',
    '...cc...',
    '........',
  ],
  sword: [
    '......ss',
    '.....sss',
    '....sss.',
    '...sss..',
    '.y.ss...',
    '.yyy....',
    'yyy.....',
    'y.......',
  ],
  skull: [
    '.WWWWWW.',
    'WWWWWWWW',
    'WkkWWkkW',
    'WkkWWkkW',
    'WWWWWWWW',
    'WWWkkWWW',
    'WkWkkWkW',
    '.WWWWWW.',
  ],
  ladybug: [
    '..k..k..',
    '...kk...',
    '.rrkkrr.',
    'rrkrrkrr',
    'rrrkkrrr',
    'rrkrrkrr',
    '.rrkkrr.',
    '..r..r..',
  ],
  clock: [
    '..ssss..',
    '.sWWWWs.',
    'sWWkWWWs',
    'sWWkWWWs',
    'sWWkkkWs',
    'sWWWWWWs',
    '.sWWWWs.',
    '..ssss..',
  ],
}

/** 16x16: one sprite spans a 2x2 group of blocks. */
export const SPRITES_16 = {
  robot: [
    '................',
    '......kk........',
    '......kk........',
    '..ssssssssss....',
    '.sSSSSSSSSSSs...',
    '.sSccSSSSccSs...',
    '.sSccSSSSccSs...',
    '.sSSSSSSSSSSs...',
    '.sSSkkkkkkSSs...',
    '.sSSSSSSSSSSs...',
    '..ssssssssss....',
    '...sSSSSSSs.....',
    '...s.SSSS.s.....',
    '.....SSSS.......',
    '....ss..ss......',
    '................',
  ],
  frog: [
    '................',
    '..gg........gg..',
    '.gwwg......gwwg.',
    'gwkkwg....gwkkwg',
    'gwkkwggggggwkkwg',
    '.gwwggggggggwwg.',
    '..ggggggggggggg.',
    '.ggggggggggggggg',
    '.ggggggggggggggg',
    '.GggggggggggggG.',
    '.GGkkkkkkkkkkGG.',
    '..GGGGGGGGGGGG..',
    '...GGGGGGGGGG...',
    '....GG....GG....',
    '................',
    '................',
  ],
  cat16: [
    '................',
    '..oo........oo..',
    '.oppo......oppo.',
    '.ooooo....ooooo.',
    '.oooooooooooooo.',
    'oooooooooooooooo',
    'ookkwoooooowkkoo',
    'ookkkooooookkkoo',
    'oooooooooooooooo',
    'ooooookpkoooooo.',
    'oookkkkkkkkkooo.',
    'oooookkokkooooo.',
    '.ooooooooooooo..',
    '.oooooooooooooo.',
    '..oooooooooooo..',
    '................',
  ],
  slime: [
    '................',
    '................',
    '.....bbbb.......',
    '...bbccbbbb.....',
    '..bbccbbbbbb....',
    '.bbccbbbbbbbb...',
    '.bcbbbbbbbbbb...',
    'bbbbbbbbbbbbbb..',
    'bbbbwwbbbwwbbb..',
    'bbbbwwbbbwwbbb..',
    'bbbbbbbbbbbbbb..',
    'bBbbbbwwwbbbbBb.',
    'bBBbbbbbbbbbBBb.',
    '.BBBBBBBBBBBBB..',
    '..BBBBBBBBBBB...',
    '................',
  ],
  bird: [
    '................',
    '.....bbbb.......',
    '...bbbbbbbb.....',
    '..bbbbbbbbbb....',
    '..bbkwbbbbbb....',
    '.bbbbbbbbbbb.oo.',
    '.bbbbbbbbbbbooo.',
    '.bbbBBbbbbbb.oo.',
    '.bbBBBBbbbbb....',
    '.bbbBBBbwwww....',
    '..bbbbbwwwww....',
    '...bbwwwwww.....',
    '....ww..ww......',
    '....yy..yy......',
    '................',
    '................',
  ],
  crown: [
    '................',
    '................',
    '..y..........y..',
    '..yy...yy...yy..',
    '..yy..yyyy..yy..',
    '..yyy.yyyy.yyy..',
    '..yyyyyyyyyyyy..',
    '..yyyyyyyyyyyy..',
    '..yyrryyyyrryy..',
    '..yyrryybbrryy..',
    '..yyyyyybbyyyy..',
    '..yyyyyyyyyyyy..',
    '..yyyyyyyyyyyy..',
    '................',
    '................',
    '................',
  ],
  ghost: [
    '................',
    '.....SSSSSS.....',
    '...SSWWWWWWSS...',
    '..SWWWWWWWWWWS..',
    '..SWWkkWWkkWWS..',
    '..SWWkkWWkkWWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWppWWppWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWWWWWWWWS..',
    '..SWWWWWWWWWWS..',
    '..SWSWWSSWWSWS..',
    '..S.SS.SS.SS.S..',
    '................',
    '................',
  ],
  mushroom16: [
    '................',
    '.....rrrrrr.....',
    '...rrrrrrrrrr...',
    '..rrwwrrrrwwrr..',
    '..rrwwrrrrwwrr..',
    '.rrrrrrrrrrrrrr.',
    '.rrwwrrrrrrwwrr.',
    '.rrwwrrrrrrwwrr.',
    '.rrrrrrrrrrrrrr.',
    '..rrrrrrrrrrrr..',
    '....WWWWWWWW....',
    '....WWkWWkWW....',
    '....WWWWWWWW....',
    '....WWWWWWWW....',
    '.....WWWWWW.....',
    '................',
  ],
  rocket: [
    '.......kk.......',
    '......kwwk......',
    '......kwwk......',
    '.....krwwrk.....',
    '.....krwwrk.....',
    '....kswwwwsk....',
    '....kswwwwsk....',
    '...kswwwwwwsk...',
    '...ksWWWWWWsk...',
    '..krsWWWWWWsrk..',
    '..krrsWWWWsrrk..',
    '.krrr.kkkk.rrrk.',
    '......yoyo......',
    '.....yoyoyo.....',
    '......yoyo......',
    '.......yo.......',
  ],
  fox: [
    '................',
    '.oo..........oo.',
    '.oNo........oNo.',
    '.oooo......oooo.',
    '.oooooooooooooo.',
    '.oooooooooooooo.',
    '.okkooooooookko.',
    '.oooooooooooooo.',
    '..oowwwwwwwwoo..',
    '..oowwkwwkwwoo..',
    '...owwwwwwwwo...',
    '...owwwwkwwwo...',
    '....wwwwwwww....',
    '.....wwwwww.....',
    '......wwww......',
    '................',
  ],
  penguin: [
    '................',
    '.....kkkkk......',
    '....kkkkkkk.....',
    '...kkwkkwkkk....',
    '...kkwwkwwkk....',
    '...kkkyykkkk....',
    '...kkkkkkkkk....',
    '..kkkWWWWWkkk...',
    '..kkWWWWWWWkk...',
    '..kkWWWWWWWkk...',
    '..kkWWWWWWWkk...',
    '...kWWWWWWWk....',
    '...kkWWWWWkk....',
    '....kkkkkkk.....',
    '...yyy...yyy....',
    '................',
  ],
  chest: [
    '................',
    '..nnnnnnnnnnnn..',
    '.nNNNNNNNNNNNNn.',
    '.nNyyyyyyyyyyNn.',
    '.nNyNNNNNNNNyNn.',
    '.nNyyyyyyyyyyNn.',
    '.nnnnnnnnnnnnnn.',
    '.nyyyyyyyyyyyyn.',
    '.nNNNNNykyNNNNn.',
    '.nNNNNNykyNNNNn.',
    '.nNNNNNNNNNNNNn.',
    '.nNNNNNNNNNNNNn.',
    '.nnnnnnnnnnnnnn.',
    '................',
    '................',
    '................',
  ],
  potion: [
    '................',
    '......SSSS......',
    '......SwwS......',
    '......SwwS......',
    '.....SSwwSS.....',
    '.....SwwwwS.....',
    '....SwwwwwwS....',
    '....SwPPPPwS....',
    '...SwPPPPPPwS...',
    '...SPPPPPPPPS...',
    '...SPPPPPPPPS...',
    '...SPPwPPPPPS...',
    '...SPPPPPPPPS...',
    '....SPPPPPPS....',
    '.....SSSSSS.....',
    '................',
  ],
  tree16: [
    '................',
    '.......GG.......',
    '......GGGG......',
    '.....GGGGGG.....',
    '....GGGGGGGG....',
    '...GGGGGGGGGG...',
    '......GGGG......',
    '.....gggggg.....',
    '....gggggggg....',
    '...gggggggggg...',
    '..gggggggggggg..',
    '......GGGG......',
    '.......nn.......',
    '.......nn.......',
    '......nnnn......',
    '................',
  ],
  octopus: [
    '................',
    '.....PPPPPP.....',
    '....PPPPPPPP....',
    '...PPPPPPPPPP...',
    '...PPwwPPwwPP...',
    '...PPwkPPwkPP...',
    '...PPPPPPPPPP...',
    '...PPPPPPPPPP...',
    '...PPpPPPPpPP...',
    '...PPPPPPPPPP...',
    '...PPPPPPPPPP...',
    '..PP.PP.PP.PP...',
    '..P..P..P..P....',
    '.PP..PP.PP..PP..',
    '................',
    '................',
  ],
  boat: [
    '................',
    '.......k........',
    '.......kWW......',
    '.......kWWWW....',
    '.......kWWWWWW..',
    '.......kWWWW....',
    '.......kWW......',
    '.......k........',
    '..nnnnnnnnnnnn..',
    '..nNNNNNNNNNNn..',
    '...nnnnnnnnnn...',
    '....bbbbbbbb....',
    '..bbbbbbbbbbbb..',
    '................',
    '................',
    '................',
  ],
}

/** 32x32: one sprite spans a 4x4 group of blocks — neighbours hold related-but-different detail. */
export const SPRITES_32 = {
  dino: [
    '................................',
    '................................',
    '..................gggggggggg....',
    '.................gggggggggggg...',
    '................gggggggggggggg..',
    '................gggkkgggggggggg.',
    '................gggkkgggggggggg.',
    '................gggggggggggggwwg',
    '.............gggggggggggggggwwwg',
    '...........gggggggggggggggggggg.',
    '..........gggggggggggggggggg....',
    '.........gggggggggggggggg.......',
    '....GG..gggggggggggggggg........',
    '...GGGG.ggggggggggggggg.........',
    '..GGGGGGgggggggggggggg..........',
    '.GGGGGGGgggggggggggggg..........',
    'GGGGGGGGgggggggggggggg..........',
    '.GGGGGGGgggggggggggggg..........',
    '..GGGGGGgggggggggggggg..........',
    '...GGGGGgggggggggggggg..........',
    '....GGGGgggggggggggggg..........',
    '......GGgggggggggggggg..........',
    '........gggggggggggggg..........',
    '........gggggg..gggggg..........',
    '........ggggg....ggggg..........',
    '.......ggggg.....ggggg..........',
    '.......ggggg.....ggggg..........',
    '......gggggg....gggggg..........',
    '.....GGGGGG.....GGGGGG..........',
    '................................',
    '................................',
    '................................',
  ],
  knight: [
    '................................',
    '................................',
    '..........sssssssssss...........',
    '.........sSSSSSSSSSSSs..........',
    '........sSSSSSSSSSSSSSs.........',
    '........sSSkkkkkkkkkSSs.........',
    '........sSSkttttttttkSSs........',
    '........sSSkttwttwttkSSs........',
    '........sSSkttttttttkSSs........',
    '.........SSkttkkkkttkSS.........',
    '..........kkttttttttkk..........',
    '...........sssssssss............',
    '.........sssSSSSSSSsss..........',
    '.....y...ssSSSSSSSSSss...bbb....',
    '.....y..sSSSSSSSSSSSSSs..bbbbb..',
    '.....y..sSSSyyyyySSSSSs..bbbbb..',
    '.....y..sSSSyyyyySSSSSs..bbbbb..',
    '.....y..sSSSSSSSSSSSSSs..bbbbb..',
    '.....y..sSSSSSSSSSSSSSs...bbb...',
    '.....y...sSSSSSSSSSSSs....b.....',
    '..yyyyy..ssSSSSSSSSSss..........',
    '.....y....kkkkkkkkkk............',
    '.....y....kSSSSSSSSk............',
    '..........kSSSSSSSSk............',
    '..........SSSS..SSSS............',
    '..........SSSS..SSSS............',
    '..........SSSS..SSSS............',
    '.........SSSSS..SSSSS...........',
    '........kkkkkk..kkkkkk..........',
    '................................',
    '................................',
    '................................',
  ],
  ship: [
    '................................',
    '..............kkkk..............',
    '.............kwwwwk.............',
    '............kwwwwwwk............',
    '...........kwwwwwwwwk...........',
    '..........kwwwwwwwwwwk..........',
    '..........kwwccccccwwk..........',
    '.........kwwccbbbbccwwk.........',
    '.........kwwccbbbbccwwk.........',
    '.........kwwwccccccwwwk.........',
    '........kwwwwwwwwwwwwwwk........',
    '........kwwwwwwwwwwwwwwk........',
    '.......kwwwwwwwwwwwwwwwwk.......',
    '.......kwrrwwwwwwwwwwrrwk.......',
    '......kwwrrwwwwwwwwwwrrwwk......',
    '......kwwrrwwwwwwwwwwrrwwk......',
    '.....kwwwrrwwwwwwwwwwrrwwwk.....',
    '.....kwwwwwwwwwwwwwwwwwwwwk.....',
    '....kwwwwwwwwwwwwwwwwwwwwwwk....',
    '....kwwwwwwwwwwwwwwwwwwwwwwk....',
    '...kwwwwwwwwwwwwwwwwwwwwwwwwk...',
    '...kwwwwwwwwwwwwwwwwwwwwwwwwk...',
    '..kwwrrwwwwwwwwwwwwwwwwwwrrwwk..',
    '..kwwrrwwwwwwwwwwwwwwwwwwrrwwk..',
    '..kkkkkwwwwwwwwwwwwwwwwwwkkkkk..',
    '....kkkkkk............kkkkkk....',
    '....kSSSSk............kSSSSk....',
    '.....oooo..............oooo.....',
    '.....yyyy..............yyyy.....',
    '......yy................yy......',
    '................................',
    '................................',
  ],
  castle: [
    '................................',
    '................................',
    '..ss..ss.....ss..ss.....ss..ss..',
    '..ss..ss.....ss..ss.....ss..ss..',
    '..ssssss.....ssssss.....ssssss..',
    '..sSSSSs.....sSSSSs.....sSSSSs..',
    '..sSSSSs.....sSSSSs.....sSSSSs..',
    '..sSkkSs.....sSkkSs.....sSkkSs..',
    '..sSkkSs.....sSkkSs.....sSkkSs..',
    '..sSSSSs.....sSSSSs.....sSSSSs..',
    '..ssssssssssssssssssssssssssss..',
    '..sSSSSSSSSSSSSSSSSSSSSSSSSSSs..',
    '..sSSkkSSSSSSSSSSSSSSSSSSkkSSs..',
    '..sSSkkSSSSSSSSSSSSSSSSSSkkSSs..',
    '..sSSSSSSSSSSSSSSSSSSSSSSSSSSs..',
    '..sSSSSSSSSSnnnnnnnnSSSSSSSSSs..',
    '..sSSSSSSSSSnnnnnnnnSSSSSSSSSs..',
    '..sSSSSSSSSSnnkkkknnSSSSSSSSSs..',
    '..sSSSSSSSSSnnkkkknnSSSSSSSSSs..',
    '..sSSSSSSSSSnnkkkknnSSSSSSSSSs..',
    '..sSSSSSSSSSnnkkkknnSSSSSSSSSs..',
    '..sSSSSSSSSSnnkkkknnSSSSSSSSSs..',
    '..ssssssssssssssssssssssssssss..',
    'gggggggggggggggggggggggggggggggg',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  owl: [
    '................................',
    '.........nn..........nn.........',
    '........nnnn........nnnn........',
    '.......nnnnnnn....nnnnnnn.......',
    '......nnnnnnnnnnnnnnnnnnnn......',
    '.....nnnnnnnnnnnnnnnnnnnnnn.....',
    '....nnnnnnnnnnnnnnnnnnnnnnnn....',
    '....nnnwwwwwwnnnnwwwwwwnnnn.....',
    '....nnwwwwwwwwnnwwwwwwwwnnnn....',
    '....nnwwkkkkwwnnwwkkkkwwnnnn....',
    '....nnwwkkkkwwnnwwkkkkwwnnnn....',
    '....nnwwwwwwwwnnwwwwwwwwnnnn....',
    '.....nnwwwwwwyywwwwwwwwnnnn.....',
    '.....nnnnnnnnyynnnnnnnnnnnn.....',
    '.....nnnnnnnnnnnnnnnnnnnnnn.....',
    '....nnnnNNNNnnnnNNNNnnnnnnnn....',
    '....nnnnNNNNnnnnNNNNnnnnnnnn....',
    '....nnnnnnnnnnnnnnnnnnnnnnnn....',
    '....nnnnNNNNnnnnNNNNnnnnnnnn....',
    '....nnnnNNNNnnnnNNNNnnnnnnnn....',
    '.....nnnnnnnnnnnnnnnnnnnnnn.....',
    '.....nnnnNNNNnnnnNNNNnnnnnn.....',
    '......nnnnnnnnnnnnnnnnnnnn......',
    '.......nnnnnnnnnnnnnnnnnn.......',
    '........nnnnnnnnnnnnnnnn........',
    '.......yyyy..........yyyy.......',
    '......yyyyyy........yyyyyy......',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  cat32: [
    '................................',
    '................................',
    '...oo......................oo...',
    '...ooo....................ooo...',
    '...oppo..................oppo...',
    '...opppo................opppo...',
    '...oppppo..............oppppo...',
    '...ooooooo............ooooooo...',
    '...oooooooooooooooooooooooooo...',
    '..oooooooooooooooooooooooooooo..',
    '.oooooooooooooooooooooooooooooo.',
    '.oooooooooooooooooooooooooooooo.',
    '.oooooowwkkwwoooooowwkkwwoooooo.',
    '.oooooowwkkwwoooooowwkkwwoooooo.',
    '.oooooowwwwwwoooooowwwwwwoooooo.',
    '.oooooooooooooooooooooooooooooo.',
    '.ooooooooooooopkpoooooooooooooo.',
    '.oooooooooookkkkkkkkoooooooooooo',
    '.oooooooooookkookkoooooooooooooo',
    '.oooooooooooooooooooooooooooooo.',
    '.oooooooooooooooooooooooooooooo.',
    '..oooooooooooooooooooooooooooo..',
    '..oooooooooooooooooooooooooooo..',
    '...oooooooooooooooooooooooooo...',
    '...oooooooooooooooooooooooooo...',
    '....oooooooooooooooooooooooo....',
    '.....oooooooooooooooooooooo.....',
    '......oooooooooooooooooooo......',
    '.......oooooo......oooooo.......',
    '.......oooooo......oooooo.......',
    '................................',
    '................................',
  ],
}

/**
 * Art authored as text is art that silently loses a character. Every sprite is checked on
 * import, so a mis-typed row fails the generator rather than shifting half a picture left.
 */
function check(name, size, rows) {
  if (rows.length !== size) throw new Error(`sprite ${name}: ${rows.length} rows, expected ${size}`)
  rows.forEach((row, y) => {
    if (row.length !== size) throw new Error(`sprite ${name} row ${y}: ${row.length} chars, expected ${size}`)
    for (const ch of row) {
      if (!(ch in C)) throw new Error(`sprite ${name} row ${y}: unknown colour '${ch}'`)
    }
  })
}

for (const [name, rows] of Object.entries(SPRITES_8)) check(name, 8, rows)
for (const [name, rows] of Object.entries(SPRITES_16)) check(name, 16, rows)
for (const [name, rows] of Object.entries(SPRITES_32)) check(name, 32, rows)

export function spriteColor(ch) {
  return C[ch] ?? null
}
